### ISSUE TITLE
Nightly CI runs often fail

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-study-template#234]
Nightly runs often fail bc the testing data cannot be downloaded properly. Example traceback:

```python
Traceback (most recent call last):
  File "/home/circleci/miniforge/lib/python3.8/site-packages/openneuro/download.py", line 241, in _download_files
    await asyncio.gather(*download_tasks)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/openneuro/download.py", line 146, in _download_file
    async with (
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 1830, in __aenter__
    self.response = await self.client.send(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/home/circleci/miniforge/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
```
This needs to be addressed upstream in `openneuro-py`: currently it will auto-retry with an exponential backoff only for server responses indicating server overload etc.; but all timeouts are set to, I believe, 5 seconds. We need to retry also in case of an exceeded timeout.

**Comment by hoechenberger** [comment]
Another one:

```python
Traceback (most recent call last):
  File "tests/run_tests.py", line 120, in <module>
    run_tests(test_suite, download=download)
  File "tests/run_tests.py", line 73, in run_tests
    fetch(dataset)
  File "tests/run_tests.py", line 16, in fetch
    main(dataset)
  File "/home/circleci/project/tests/download_test_data.py", line 69, in main
    _download(ds_name=ds_name, ds_path=ds_path)
  File "/home/circleci/project/tests/download_test_data.py", line 50, in _download
    download_func(ds_name=ds_name, ds_path=ds_path)
  File "/home/circleci/project/tests/download_test_data.py", line 34, in _download_via_openneuro
    openneuro.download(dataset=DATASET_OPTIONS[ds_name]['openneuro'],
  File "/home/circleci/miniforge/lib/python3.8/site-packages/openneuro/download.py", line 297, in download
    metadata = _get_download_metadata(base_url=default_base_url,
  File "/home/circleci/miniforge/lib/python3.8/site-packages/openneuro/download.py", line 41, in _get_download_metadata
    response = httpx.get(url)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_api.py", line 181, in get
    return request(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_api.py", line 93, in request
    return client.request(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 733, in request
    return self.send(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 767, in send
    response = self._send_handling_auth(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/home/circleci/miniforge/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: The read operation timed out
```

**Comment by hoechenberger** [comment]
I'm addressing this in https://github.com/hoechenberger/openneuro-py/pull/29
We're already using this branch for downloading our testing data. Seems to be working nicely so far!!
