### ISSUE TITLE
Could not find input data file matching

### ISSUE THREAD

**Issue by soichih** [mne-tools/mne-study-template#61]
Hello! I am completely new to EEG/MEG let alone mne-tools, but I am trying my best to get this software working on my computer. 

I've downloaded a dataset from openneuro (ds000247 - OMEGA Resting State), and trying to run mne-study-template. When I run "make sensor", I ran into the following error message.

```
hayashis@haswell:~/git/mne-study-template(master*) $ export BIDS_ROOT=/mnt/3t/testdata/ds000247-download
hayashis@haswell:~/git/mne-study-template(master*) $ make sensor
python3 01-import_and_filter.py

Processing subject: 0006
------------------------
Traceback (most recent call last):
  File "01-import_and_filter.py", line 155, in <module>
    main()
  File "01-import_and_filter.py", line 151, in main
    config.sessions))
  File "01-import_and_filter.py", line 149, in <genexpr>
    parallel(run_func(subject, run, session) for subject, run, session in
  File "01-import_and_filter.py", line 77, in run_filter
    '"{}"'.format(search_str))
ValueError: Could not find input data file matching: "/mnt/3t/testdata/ds000247-download/sub-0006/ses-0001/meg/sub-0006_ses-0001_task-noise_run-01_meg*"
make: *** [Makefile:14: sensor] Error 1
```

Could you help me troubleshoot this problem?

**Comment by jasmainak** [comment]
Does it work if you just do one subject? In the config file

**Comment by hoechenberger** [comment]
Closing for lack of activity. Feel free to reopen if needed.
